# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: >-
        cd server &&
        go build -o ../build/ps-server ./cmd/pubsub &&
        cd ../example &&
        go build -o ../build/queue ./queue &&
        go build -o ../build/subscriber ./subscriber &&
        go build -o ../build/publisher ./publisher &&
        go build -o ../build/request ./request

    - name: Test
      run: >-
        cd core &&
        go test . -cover -race -coverprofile=cover.out &&
        grep -v "mock_" cover.out > cover.tmp && mv cover.tmp cover.out &&
        go tool cover -func cover.out | grep total &&
        cd ../server &&
        go test . -cover -race -coverprofile=cover.out &&
        grep -v "mock_" cover.out > cover.tmp && mv cover.tmp cover.out &&
        go tool cover -func cover.out | grep total &&
        cd ../client &&
        go test . -cover -race -coverprofile=cover.out &&
        grep -v "mock_" cover.out > cover.tmp && mv cover.tmp cover.out &&
        go tool cover -func cover.out | grep total
